keys:
  - &ramge age1e44u5h220c68anq30kaz8g9e6xnylnwsygnpg2667c76993zf9mstfpcn4
  - &mkuu1 age1duc22405mpn8jarpc9ukkhy4l7uvs7ngkgw6u3c897mfagguceusla4m5c

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *ramge
          - *mkuu1
